### ISSUE TITLE
The items indicator on Home screen doesn't match the design

### ISSUE THREAD

**Issue by hoangnguyen92dn** [tngcanh07/survey-android#28]
We'd expect the application should follow the design on Figma, would it be possible to update to match the design, please? 
 
| App | Figma |
| - | - |
| <img src="https://user-images.githubusercontent.com/6950766/126513877-35fbd6a2-400b-41f6-9da4-b4b4ac1e0403.png" width=250> | <img src="https://user-images.githubusercontent.com/6950766/126513481-f4fe4896-35b9-48bd-a284-13663252a357.png" width=250> |

**Comment by tngcanh07** [comment]
Thank you. I totally agree it should match the design.

I just a question, how the design looks like if user has a lot of surveys (20, 50, or event 100), screen will not have enough space to display the indicator.

Do you have any suggestions?

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 👍  I'd suggest making the horizontal scrollable for the indicators if there is not enough space to display all the items.
