### ISSUE TITLE
Handle navigation on MainActivity with Navigator

### ISSUE THREAD

**Issue by hoangnguyen92dn** [tngcanh07/survey-android#30]
As I see, the created Navigators from your current implement are defined as `interface`, and the details will be implemented on the MainActivity. Ideally, I think creating the Navigator is a nice approach to handle navigation to the destination screens separately from the Activity/Fragment.  How do you think about getting rid of navigation logic outside the Activity?

**Comment by tngcanh07** [comment]
@hoangnguyen92dn from my point of view,  the logic of navigation is cohesive with the host (Activity), it depends on the technical usage (in this case is navigation component), and if the fragment is attached to different activities, there could be different implementations of navigator interfaces (why not). That is why I put the implementation of navigators into Activity.

you have a valid point that if we take the implementation out of the activity/fragment, the complexity of activity could reduce, even if the activity hosts hundreds of fragments, but it needs an internal navigationController from the host (Activity)

Both approaches have cons and pros. I'd like to make it consistent everywhere in the team. so I'm happy to follow.

 Or do you see other points?

**Comment by hoangnguyen92dn** [comment]
> it depends on the technical usage (in this case is navigation component), and if the fragment is attached to different activities, there could be different implementations of navigator interfaces (why not). That is why I put the implementation of navigators into Activity.

@tngcanh07 Thanks for clarifying your idea 👍  As you said about different implementations of navigator, here is the point from my opinion, why don't we create different instances of Navigator class and use DI to inject the specific navigator to the expected Activity/Fragment for usage? The implementation of the navigator interface could be different in each implemented class. Furthermore, we could reuse the navigation logic if needed rather than have to always implement details in Activity/Fragment. Does it make sense to you?

**Comment by tngcanh07** [comment]
thanks for your answers. yes it makes sense for multiple implementations of navigator

and how do you think about using NavigationController outside MainActivity? my concern is: NavigationController has a lifecycle and it depends on the lifecycle of MainActivity.

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 Regarding the lifecycle of Navigator, agree that it would belong to the Activity's lifecycle. And with the DI libraries (Dagger or Hilt), we could do it easily by using the `Scope` annotations.

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 From the `main_navigation`, I see you have to pass each field in the `<argument>` (id, title, description, image URL) to passing to the details page, let's imagine that we have an object with a dozen of properties, so there is a lot of `<argument>` in the navigator?

https://github.com/tngcanh07/survey-android/blob/a157d2100aec9f1e9f15669690e741df7afae887/app/src/main/res/navigation/main_navigation.xml#L93-L115

**Comment by tngcanh07** [comment]
@hoangnguyen92dn I suppose passing the object id and main information to detail page. and the full data will be loaded from the database or from backend

There's another approach that putting Serialization or Parcelable object to bundle, but I rarely do it, because it will introduce unnecessarily dependency between 2 screens.

does it make sense to your concern?

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 Yeah. My idea is to use a bundle in the navigation graph. Can you please clarify this point in detail? I can't catch this idea 🤔 

> because it will introduce unnecessarily dependency between 2 screens.

**Comment by tngcanh07** [comment]
@hoangnguyen92dn yup, if using bundle, there must be a shared parcelable/serialization model between start and destination fragment, usually the model comes from start fragment. 
and it's getting complicated when the detail can be opened from multiple places. e.g: from survey list, or deeplink, or advertising...

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 Agree that point 👍  sometimes details screen could be opened from Deeplink so bundle can't handle this case. In normal case, we might add the options to define the bund could be `null`. Thanks for sharing in details.
