### ISSUE TITLE
Suggestion about effective Kotlin implementation

### ISSUE THREAD

**Issue by hoangnguyen92dn** [tngcanh07/survey-android#32]
- [x] Would it be possible to use another scope function to get rid of `it` from the `also` block?

https://github.com/tngcanh07/survey-android/blob/a6b3c5a8b6e8cafc7afc23be075af6d924aeafc3/data/src/main/java/com/tn07/survey/data/oauth/datasources/local/OAuthLocalDataSourceImpl.kt#L60-L77

- [x] There are some places you are using `companion object` to define constants and it looks like the `private static final` from the old Java style. With Kotlin, I'd suggest defining the constants as the top class level. 

https://github.com/tngcanh07/survey-android/blob/a6b3c5a8b6e8cafc7afc23be075af6d924aeafc3/data/src/main/java/com/tn07/survey/data/oauth/datasources/local/OAuthLocalDataSourceImpl.kt#L119-L127

**Comment by tngcanh07** [comment]
1, good catch, I will adapt it
2, there's a lot of discussions about defining constants within Kotlin community, seems both ways are acceptable in the community. they both are doing the same thing and creating new classes to store constants in byte-code level.
I totally agree that we should make it consistent across the team.
I'm just curious if you  have other view points on it?

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 About the constants defination, I agree that it is always a question on the community. But it's not just to make it consistent across the team. There is a recommendation from JetBrains team:

> The recommended practice is to never use `object` for creating namespaces, and to always use top-level declarations when possible.

FYI: https://discuss.kotlinlang.org/t/best-practices-for-top-level-declarations/2198/3

Besides that, defining const inside `companion object` or `Object` in case you want to create a single class for constants is similar to what we often do with Java style. So from your current implementation, there are `private` constants to use inside the class scope, that's why I suggest to define the constants on top-level
