### ISSUE TITLE
Clean code checklist 🧹 

### ISSUE THREAD

**Issue by hoangnguyen92dn** [tngcanh07/survey-android#33]
🕵️‍♂️  There are some issues such as unused imports, unnecessary public modifiers... Let's clean minor things to make up your code better 🌟  I just list a few files for example here so please double-check the rest of the files 💪 

https://github.com/tngcanh07/survey-android/blob/a6b3c5a8b6e8cafc7afc23be075af6d924aeafc3/data/src/main/java/com/tn07/survey/data/api/transfomers/ApiCompletableTransformer.kt#L3-L13

https://github.com/tngcanh07/survey-android/blob/a6b3c5a8b6e8cafc7afc23be075af6d924aeafc3/app/src/main/java/com/tn07/survey/features/login/uimodel/FormError.kt#L7-L9

**Comment by tngcanh07** [comment]
I forgot those files, thank you for pointing it out. I will run some analysis tools to catch those stuffs.
