### ISSUE TITLE
A minor suggestion to clarify the requires parameters

### ISSUE THREAD

**Issue by hoangnguyen92dn** [tngcanh07/survey-android#34]
Would it be possible to use annotation to clarify the `messageId: Int` in this extension function?

https://github.com/tngcanh07/survey-android/blob/a6b3c5a8b6e8cafc7afc23be075af6d924aeafc3/app/src/main/java/com/tn07/survey/features/common/ToastExt.kt#L10-L12

**Comment by tngcanh07** [comment]
good catch! thanks man. I didn't use this feature a lot in Kotlin because the build-time verification doesn't work as well as for Java.

but it may a good hint when reading the code, I definitely adapt it 👍

**Comment by tngcanh07** [comment]
this method hasn't been used anywhere in the app, so I removed it.
